### PR TITLE
[Merge] All scene from Main Menu to Outro

### PR DESCRIPTION
**Pull request by nnarct**
Merge latest updates from all developers

This merge includes the latest changes from various development branches.
It incorporates feature additions, bug fixes, and improvements contributed
by different team members. Review the individual commits for details.

### CODE REVIEW

**Review by nnarct — COMMENTED** [review]
I reviewed it carefully. LGTM.

**Review by natchasuha — APPROVED** [review]
I reviewed it carefully.

**Review by JakkrapanPt — COMMENTED** [review]
I reviewed it carefully.

**Review by JakkrapanPt — APPROVED** [review]
I reviewed it carefully.

**Review by wishcream — COMMENTED** [review]
I review it carefully

**Review by PARIIXZ — APPROVED** [review]
I think these code is very great. It's okay to merge.

**Review by wishcream — APPROVED** [review]
I reviewed it carefully.

**Review by Sarunnnnnnnn — COMMENTED** [review]
I checked all of them and personally think that these are super works.

**Pull request merged**
